version: '3.3'

services:

  redis:
    image: redis:${redis_version}
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    healthcheck:
      test:  redis-cli ping | grep -q '^PONG' || exit 1

  zookeeper:
    image: confluentinc/cp-zookeeper:${zookeeper_version}
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:${kafka_version}
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: BROKER://0.0.0.0:9091,PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,BROKER://localhost:9091
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
